# Generated by Django 4.0.1 on 2022-01-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['movie__title', 'show_time']},
        ),
    ]
