# Generated by Django 4.0.1 on 2022-01-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
