# Generated by Django 4.0.1 on 2022-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_rating_movie_sub_title_movie_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
