# Generated by Django 4.0.1 on 2022-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
